<a href="https://colab.research.google.com/github/Thuoq/Practice-Tensorflow-Certificate/blob/main/00_tensorflow_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover soem of the most fundamental concepts of tensors using TensorFlow

More specifically,we're going to cver:
* Introduction to tensor
* Getting infromation from tensoor
* Manipulating tensor
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python)
* Using GPUs with Tensorflow (or TPUs)
* Exercise to try yourself

# Introduction to Tensor

In [ ]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


# Create tensor with `tf.constant()`

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the num of dimentions of a tensor (`ndim`)
scalar.ndim

0

In [ ]:
#Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Chck the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                       [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
threeDimension = tf.constant([[[10,8]
                               ,[20,1]
                               ,[0,1]]])
threeDimension

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[10,  8],
        [20,  1],
        [ 0,  1]]], dtype=int32)>

In [ ]:
# Create another matrix 
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

# Create tensors `Tf.Variable`

In [ ]:
# Creat the same tensor with `tf.Variable()`
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change on of the elements in our change tensor
#changeable_tensor[0] = 11

TypeError: ignored

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Let's try change to unchangeable tensor 
#unchangeable_tensor[0].assgin(7)

AttributeError: ignored

**Note**: Trong thực tế bạn cần phải quyết đinh sử dụ `tf.constants` hoặc `tf.Variable` để tạo **tensor**. Nhưng cứ dùng dùng thằng constants did để change nếu mình thay đổi hehe  ^^

####Create random tensors


In [ ]:
# Create twi random but the same tensor
random_1 = tf.random.Generator.from_seed(7) # set seed for repor
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

 ### Suffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valueable for when u want to shuffle your data so so the inherent order doesn't effect learning)
not_suffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
not_suffled.ndim

2

In [ ]:
not_suffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffle our non-shuffled tensor 
tf.random.set_seed(42)
tf.random.shuffle(not_suffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

**Exercise:** read thourhg tensorflow documentation on randome generation

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as operation level random seed 
> Rules 4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


### Other ways create tensor 

In [ ]:
# Create a tensor of all ones
tf.ones((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros((10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# You can also turn NumPy arrays into tensors

The main difference betwwen NumPY arrays and TensorFlow tensors is that tensors can be run on GPU faster 

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create a numpy array 1->25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:

A = tf.constant(numpy_A,shape=(3,8)) ## must 2*3*4 -> the same 24 above
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim,B.ndim

(2, 1)

### Getting information from tensors 
When dealing with tensors you probal wan to aware of the folowing attributes:
* Shape 
* Rank
* Axis or dimension
* Size 

In [ ]:
# Create a rank 4 tensors ( 4 dimensions)

rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the las axis",rank_4_tensor.shape[-1])
print("The total of elemnts in our tensor",tf.size(rank_4_tensor))
print("The total of elemnts in our tensor",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the las axis 5
The total of elemnts in our tensor tf.Tensor(120, shape=(), dtype=int32)
The total of elemnts in our tensor 120


### Indexing Tensors
Tensors can be indexed just like Python lists

In [ ]:
some_list= [1,2,3,4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first 2 element of each dimension
rank_4_tensor[:2,:2,:2,:2 ]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final
rank_4_tensor[:1,:1,:1,:]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
 # Create a rank 2 tesor (2diménions)
 rank_2_tensor = tf.constant([[10,7],[3,4]])
 rank_2_tensor.ndim,rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [ ]:
# Get the last item of each of row of our rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaix
tf.expand_dims(rank_2_tensor,axis=-1) # "-1" means expand the final aix

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Manipulating tensor (tensor operation)
**Basic Operations**
`+`,`-`,`*`,`/` 

In [ ]:
# You can add values to a tensor using the addition operato
tensor = tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchange
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction if u want
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow func 
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor_change = tf.Variable([[10,8],[1,2]])
tensor_change+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 18],
       [11, 12]], dtype=int32)>

In [ ]:
tensor_change

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  8],
       [ 1,  2]], dtype=int32)>

**Matrix mutiplciation**

In Ml, matrix mutiplication is one of mosthe common tesnor 

1. inner dimension must match
2. the reuslting matrix match 
(M,N) mus (N,X) => (M,X)

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix mutiplication with python operator "@"
tensor @ tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1504, 1239],
       [ 531,  442]], dtype=int32)>

In [ ]:
# Create tensor (3,2) 
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
#create tensor (3,3)
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

tf.matmul(tf.transpose(X) , y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.transpose(X) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The Dot product**
Matrix multiplication is cũng rêred to as the dot product

Bạn có thể xử dlys matrix multiplication sử dụng : 
* `tf.matmul()`
*`tf.tesnordot()`

# Changing the datatype of a tensor 

In [ ]:
# Create a new tensor with default datatype (float 32)
B = tf.constant([1.7,7.5])
B.dtype

tf.float32

In [ ]:
C = tf.constant([6,210])
C.dtype

tf.int32

In [ ]:
#change from flaot 32 to flaot 16
D = tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.5], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from in32 to float 32
E = tf.cast(C,dtype=tf.float32)

In [ ]:
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([  6., 210.], dtype=float32)>

### Aggregating tensor

Aggregating tensors = condesing them from multiple values down to a smaller amount of values.

In [ ]:
D = tf.constant([-7,19])
tf.abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 19], dtype=int32)>

Let's go through the following froms of aggregation:
* Get the min
* Get the max
* Get the mean of tensro
* get the sum 

In [ ]:
# Creat a random tensor with values beween 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 7, 92, 63, 80, 83, 24, 81, 49, 26, 16, 45, 35, 66, 85, 20, 70, 15,
       79, 92, 42, 86, 10, 73, 10,  0, 30, 52,  8, 17, 43, 62, 97, 73, 49,
       38, 86, 20, 83, 75, 59, 35, 12, 48, 43, 67, 58, 59, 15, 44, 88])>

In [ ]:
# find the minimun 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# find the maximun 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# find the mean 
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
# find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2510>

**Exercise**: With that we're learn , find var and std 

In [ ]:
E = tf.cast(E,dtype=tf.float32)
tf.math.reduce_std(E)
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=775.4801>

## Find the the positional maximun and minimum 

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 7., 92., 63., 80., 83., 24., 81., 49., 26., 16., 45., 35., 66.,
       85., 20., 70., 15., 79., 92., 42., 86., 10., 73., 10.,  0., 30.,
       52.,  8., 17., 43., 62., 97., 73., 49., 38., 86., 20., 83., 75.,
       59., 35., 12., 48., 43., 67., 58., 59., 15., 44., 88.],
      dtype=float32)>

In [ ]:
# Create a new tensor for finding positional minimun and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])

In [ ]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the position max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Ubdex ib our larrgest values position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the value of F maxx 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

### Squeezing a tensor (remoall all single dimensions)

In [ ]:
# Create a tensor to get tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [ ]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G) # remove dimentions have size 1
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
some_list = [0,1,2,3] # cound be red , green , blue ,purple

# One hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specifi custom values for on hot encoding 
tf.one_hot(some_list,depth=4,on_value="I love Sambi",off_value="papa")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love Sambi', b'papa', b'papa', b'papa'],
       [b'papa', b'I love Sambi', b'papa', b'papa'],
       [b'papa', b'papa', b'I love Sambi', b'papa'],
       [b'papa', b'papa', b'papa', b'I love Sambi']], dtype=object)>

In [ ]:
# Squaring, log , square root
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square root
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors vs Numpy

In [ ]:
# Create a tẻno diectly from a Numpu 
J = tf.constant(np.array([3.,7.,10.]))
J


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#convert to numpy
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default types of each arre slightly diffferent 
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype, tensor_J.dtype # np is float64, tf is 32

(tf.float64, tf.float32)