<a href="https://colab.research.google.com/github/Thuoq/Practice-Tensorflow-Certificate/blob/main/TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
vector = tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
matrix = tf.constant([[1,2,4],[2,1,2]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [2, 1, 2]], dtype=int32)>

2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
def show_rank_shape_size(tensor):
  print(tensor.shape,tf.size(tensor),tensor.ndim)

In [ ]:
show_rank_shape_size(scalar)
show_rank_shape_size(vector)
show_rank_shape_size(matrix)

() tf.Tensor(1, shape=(), dtype=int32) 0
(3,) tf.Tensor(3, shape=(), dtype=int32) 1
(2, 3) tf.Tensor(6, shape=(), dtype=int32) 2


3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
ten_3 = tf.constant(np.random.rand(5,300))
ten_3

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.3757763 , 0.2496846 , 0.16192394, ..., 0.60702997, 0.16203366,
        0.25091867],
       [0.51603985, 0.1032115 , 0.18244388, ..., 0.02358556, 0.70973477,
        0.05844744],
       [0.31569682, 0.94100217, 0.19351137, ..., 0.10271868, 0.28068468,
        0.31484396],
       [0.84403928, 0.47172076, 0.04063454, ..., 0.73536587, 0.78711622,
        0.31234253],
       [0.41547784, 0.58194827, 0.07171979, ..., 0.25601614, 0.64866452,
        0.89220249]])>

In [ ]:
ten_3_b = tf.constant(np.random.rand(5,300))
ten_3_b

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.11603955, 0.09126001, 0.06699339, ..., 0.89527652, 0.91113281,
        0.9341563 ],
       [0.43612244, 0.57124772, 0.99232935, ..., 0.54533937, 0.18668151,
        0.99992303],
       [0.44373679, 0.17899051, 0.47686309, ..., 0.12952713, 0.55474885,
        0.76044826],
       [0.10021507, 0.49112844, 0.8913423 , ..., 0.69983288, 0.86524536,
        0.68423717],
       [0.22900945, 0.56781389, 0.27803293, ..., 0.61731453, 0.91137256,
        0.40100695]])>

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
ten_3 * ten_3_b

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.04360491, 0.02278622, 0.01084783, ..., 0.54345968, 0.14763418,
        0.23439726],
       [0.22505656, 0.05895934, 0.18104442, ..., 0.01286213, 0.13249436,
        0.05844294],
       [0.14008629, 0.16843045, 0.09227843, ..., 0.01330486, 0.1557095 ,
        0.23942254],
       [0.08458546, 0.23167548, 0.03621928, ..., 0.51463322, 0.68104865,
        0.21371636],
       [0.09514835, 0.33043831, 0.01994046, ..., 0.15804248, 0.59117505,
        0.3577794 ]])>

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.matmul(ten_3,tf.transpose(ten_3_b))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[76.83947644, 74.84253106, 74.01431994, 73.12967436, 72.60098377],
       [73.01452494, 73.63599201, 74.85253265, 71.82422572, 70.09288076],
       [73.41441621, 70.31615717, 73.21872773, 72.07707609, 69.6287792 ],
       [70.85738937, 74.55734278, 75.62285715, 70.9664762 , 70.46212301],
       [77.68626612, 75.81794252, 80.79705544, 74.41312325, 71.0091733 ]])>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
ten_6 = tf.constant(np.random.rand(244,244,3))
ten_6

<tf.Tensor: shape=(244, 244, 3), dtype=float64, numpy=
array([[[0.33217767, 0.1164255 , 0.15919135],
        [0.13715526, 0.48464952, 0.28708432],
        [0.96508165, 0.70138247, 0.94355957],
        ...,
        [0.28345957, 0.60731512, 0.72040665],
        [0.83376869, 0.80053076, 0.39143241],
        [0.87527658, 0.43338099, 0.01815277]],

       [[0.40700255, 0.77858099, 0.36001296],
        [0.0079432 , 0.04487674, 0.46063696],
        [0.67864898, 0.15908415, 0.66738039],
        ...,
        [0.97079645, 0.21539174, 0.95538694],
        [0.1670013 , 0.80579882, 0.09799158],
        [0.58855697, 0.19345547, 0.5544049 ]],

       [[0.8314855 , 0.19261382, 0.38873632],
        [0.6159487 , 0.90345677, 0.83570326],
        [0.26145784, 0.9671827 , 0.60557783],
        ...,
        [0.79932344, 0.66708594, 0.47110729],
        [0.28131002, 0.59656132, 0.34302947],
        [0.08326702, 0.36618046, 0.59789231]],

       ...,

       [[0.33053694, 0.2491744 , 0.1800252 ],
        [0.11

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
tf.math.reduce_min(ten_6)

<tf.Tensor: shape=(), dtype=float64, numpy=2.8606047250967492e-06>

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
tensor_8 = tf.constant(np.random.rand(1,224,224,3))
tensor_8

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float64, numpy=
array([[[[0.1196478 , 0.32842448, 0.78197263],
         [0.89566427, 0.49761606, 0.1514527 ],
         [0.08356753, 0.14959956, 0.46667697],
         ...,
         [0.33011014, 0.19884056, 0.61812367],
         [0.71301135, 0.31732274, 0.5775631 ],
         [0.53980712, 0.4312952 , 0.2075726 ]],

        [[0.26128531, 0.19589863, 0.62977158],
         [0.20655861, 0.13508165, 0.38174816],
         [0.52037182, 0.46076689, 0.9318881 ],
         ...,
         [0.43512173, 0.20514757, 0.69120865],
         [0.58585515, 0.38667676, 0.59737114],
         [0.07746902, 0.76587421, 0.98416675]],

        [[0.67892141, 0.73690748, 0.87069967],
         [0.60882904, 0.38377102, 0.6597617 ],
         [0.68559142, 0.84254093, 0.82746847],
         ...,
         [0.21693036, 0.24470688, 0.62236851],
         [0.64011516, 0.05695867, 0.7166679 ],
         [0.53050151, 0.14788338, 0.93229616]],

        ...,

        [[0.53160695, 0.76883645, 

In [ ]:
tf.squeeze(tensor_8)

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.1196478 , 0.32842448, 0.78197263],
        [0.89566427, 0.49761606, 0.1514527 ],
        [0.08356753, 0.14959956, 0.46667697],
        ...,
        [0.33011014, 0.19884056, 0.61812367],
        [0.71301135, 0.31732274, 0.5775631 ],
        [0.53980712, 0.4312952 , 0.2075726 ]],

       [[0.26128531, 0.19589863, 0.62977158],
        [0.20655861, 0.13508165, 0.38174816],
        [0.52037182, 0.46076689, 0.9318881 ],
        ...,
        [0.43512173, 0.20514757, 0.69120865],
        [0.58585515, 0.38667676, 0.59737114],
        [0.07746902, 0.76587421, 0.98416675]],

       [[0.67892141, 0.73690748, 0.87069967],
        [0.60882904, 0.38377102, 0.6597617 ],
        [0.68559142, 0.84254093, 0.82746847],
        ...,
        [0.21693036, 0.24470688, 0.62236851],
        [0.64011516, 0.05695867, 0.7166679 ],
        [0.53050151, 0.14788338, 0.93229616]],

       ...,

       [[0.53160695, 0.76883645, 0.88819963],
        [0.38

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.


In [ ]:
tensor_9 = tf.constant([1,2,3,4,5,6,7,8,9,10])
tf.math.argmax(tensor_9)
print(tf.size(tensor_9))

tf.Tensor(10, shape=(), dtype=int32)


10. One-hot encode the tensor you created in 9.


In [ ]:
tf.one_hot(tensor_9,tf.size(tensor_9)+1)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>